pull_request_rules:
  - name: automatic merge when GitHub branch protection passes
    conditions:
      - base=master
      - label=automerge
      - -conflict
    actions:
      merge:
        method: merge
      delete_head_branch:
        force: false
  - name: dependabot auto-merging pull requests
    conditions:
      - base=master
      - author=dependabot[bot]
      - status-success=Travis CI - Pull Request
      - status-success=Travis CI - Branch
      - -conflict
    actions:
      merge:
        method: merge
      delete_head_branch:
        force: false