pull_request_rules:
  - name: automatic merge on CI success when marked with label "merge-able"
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - "label=merge-able"
    actions:
      merge:
        method: merge