pull_request_rules:
  - name: automatic merge on CI success when marked with label "merge-able"
    conditions:
      - status-success=Travis CI - Pull Request
      - status-success=Travis CI - Branch
      - label="merge-able"
    actions:
      merge:
        method: merge